/*
* Generated file
*
* Generated from: yang module name: mappingservice-impl yang module local name: mappingservice-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Sep 07 23:55:41 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.lfm.mappingservice.impl;
public class MappingServiceModuleFactory extends org.opendaylight.controller.config.yang.config.lfm.mappingservice.impl.AbstractMappingServiceModuleFactory {

}
