/*
* Generated file
*
* Generated from: yang module name: mappingservice-shell-impl yang module local name: mappingservice-shell-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Sep 25 12:24:36 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.lfm.mappingservice.shell.impl;
public class MappingServiceShellModuleFactory extends org.opendaylight.controller.config.yang.config.lfm.mappingservice.shell.impl.AbstractMappingServiceShellModuleFactory {

}
