/*
* Generated file
*
* Generated from: yang module name: msncc-provider-impl yang module local name: lfm-ncc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Aug 21 11:15:45 PDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.lispflowmapping.config.yang.netconf.impl;
public class LfmNccProviderModuleFactory extends org.opendaylight.lispflowmapping.config.yang.netconf.impl.AbstractLfmNccProviderModuleFactory {

}
