/*
* Generated file
*
* Generated from: yang module name: lfm-mappingservice-sb-impl yang module local name: lfm-mappingservice-sb
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon May 11 18:08:47 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.lfm_mappingservice_sb.impl;
public class LfmMappingServiceSbModuleFactory extends org.opendaylight.controller.config.yang.config.lfm_mappingservice_sb.impl.AbstractLfmMappingServiceSbModuleFactory {

}
