/**
* Generated file

* Generated from: yang module name: config-lisp  yang module local name: lispconfig
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Nov 06 21:01:30 IST 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.lispflowmapping.lispconfig.yang;

/**
*
*/
public class LispConfigModuleFactory extends org.opendaylight.lispflowmapping.lispconfig.yang.AbstractLispConfigModuleFactory
{


}
