/*
* Generated file
*
* Generated from: yang module name: lfm-mappingservice-impl yang module local name: lfm-mappingservice
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun May 10 23:58:02 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.lfm_mappingservice.impl;
public class LfmMappingServiceModuleFactory extends org.opendaylight.controller.config.yang.config.lfm_mappingservice.impl.AbstractLfmMappingServiceModuleFactory {

}
