/*
* Generated file
*
* Generated from: yang module name: lfm-mappingservice-impl yang module local name: lfm-mappingservice-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu May 07 18:55:34 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.lfm_mappingservice.impl;
public class LfmMappingserviceModuleFactory extends org.opendaylight.controller.config.yang.config.lfm_mappingservice.impl.AbstractLfmMappingserviceModuleFactory {

}
