/**
* Generated file

* Generated from: yang module name: config-lisp  yang module local name: lispconfig
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Nov 13 19:35:03 IST 2013
*
* Do not modify this file unless it is present under src/main directory
*/

/*
 * Copyright (c) 2014 Contextream, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.lispflowmapping.config.yang;

/**
*
*/
public class LispConfigModuleFactory extends org.opendaylight.lispflowmapping.config.yang.AbstractLispConfigModuleFactory
{


}
