/*
* Generated file
*
* Generated from: yang module name: lfm-ncc-provider-impl yang module local name: lfm-ncc-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Aug 14 11:02:55 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.lfm_netconf.impl;
public class LfmNetconfConnectorProviderModuleFactory extends org.opendaylight.controller.config.yang.config.lfm_netconf.impl.AbstractLfmNetconfConnectorProviderModuleFactory {

}
